name: Run On Docker

on:
  workflow_dispatch:
  schedule:
    # 参考 https://jasonet.co/posts/scheduled-actions/
    # note: 这里是GMT时间，北京时间减去八小时即可。如北京时间 22:30 => GMT 14:30
    # re: 目前已知在github的action runner上，访问国内相关的接口会大概率超时，如pskey和skey的获取，以及访问道聚城相关接口，故而先测试性的每日十点半运行一次，其他时候就不运行了
    # minute hour day month dayOfWeek
    - cron: '30 14 * * *' # GMT 14:30 => 北京时间 22:30
    #- cron: '30 16 * * *' # GMT 16:30（前一天） => 北京时间 00:30

jobs:
  run:

    runs-on: ubuntu-20.04
    container:
      image: fzls/djc_helper:master
      env:
        DJC_HELPER_CONFIG_TOML: ${{ secrets.DJC_HELPER_CONFIG_TOML }}
    steps:
      - name: Run
        run: |
          cd /djc_helper
          python3 main.py
